### ISSUE TITLE
uakino.club

### ISSUE THREAD

**Issue by dportvine** [braveinnovators/url-blocklist#2]
`https://uakino.club/cartoon/cartoonseries/17121-zemnovodiia-amfibiia-3-sezon.html`

`://*diia*.$document,from=~data.gov.ua|~diia.gov.ua|~fedoriv.com`

<details>
<summary>Screen</summary>

![2023-06-14_194711](https://github.com/braveinnovators/url-blocklist/assets/111344219/8664c72b-8a3f-4151-ac72-5e80f76e439e)
</details>

**Comment by serhiyguryev** [comment]
У даному випадку спрацювання правила відбувається не через назву доменного ім'я, а внаслідок транслітераційного перекладу назви .html сторінки. Тож ми не бачимо підстав для внесення доменного ім'я uakino[.]club у список виключень, оскільки вирішити ситуацію з блокуванням цієї конкретної URL-адреси можна, поставивши галочку навпроти опції «не нагадуйте мені про цей сайт».

**Comment by serhiyguryev** [comment]
У даному випадку спрацювання правила відбувається не через назву доменного ім'я, а внаслідок транслітераційного перекладу назви .html сторінки. Тож ми не бачимо підстав для внесення доменного ім'я uakino[.]club у список виключень, оскільки вирішити ситуацію з блокуванням цієї конкретної URL-адреси можна, поставивши галочку навпроти опції «не нагадуйте мені про цей сайт».

**Comment by dportvine** [comment]
Або видаливши ваш фільтр. Дякую.

**Comment by dportvine** [comment]
Жоден фiльтр не повинен ламати сайт, якщо сайт фiшинговий його блокують. Бачу, що проблема була вирiшена, дякую.

>веб-ресурс, що пропонує послуги перегляду та завантаження контенту з порушенням авторського права

Можете повідомити сюди - `https://legalcontentua.org/`. Зі святом!
