### ISSUE TITLE
Importing the filter list to AdBlock Plus causes the error "Not a valid filter list"

### ISSUE THREAD

**Issue by milichev** [braveinnovators/url-blocklist#5]
**Describe the bug**

Importing the filter list to AdBlock Plus causes the error "Not a valid filter list"

**To Reproduce**
1. Go to AdBlock Plus extension [Settings](chrome-extension://cfhdojbkjhnklbpkdaibdccddilifddb/options.html).
2. Click on the Advanced tab
3. Scroll down to FILTER LISTS
4. Click ADD FILTER LIST VIA URL
5. Enter the filter URL `https://www.awwwwesome.org/url-blocklist/url-blocklist.txt`
6. See the error (screenshot below)

**Expected behavior**

The filter is expected to be imported and used for blocking the unwanted content.

**Screenshots**

![image](https://github.com/braveinnovators/url-blocklist/assets/533183/af84abbd-843a-45d9-9688-6fd23429fcaa)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 
 - Version: 119.0.6045.124 (Official Build) (64-bit)

**Comment by serhiyguryev** [comment]
Thank you for reporting this bug, we've already fixed it (filter version: 20231113.01). 

Please let us know if you find any additional issues with Adblock Plus and our filter.
