### ISSUE TITLE
googleblog.com

### ISSUE THREAD

**Issue by dportvine** [braveinnovators/url-blocklist#6]
**Describe the bug**
Blocked by uBO

**To Reproduce**
1. Go to `https://www.google.com/search?q=chrome+what%27s+new`
2. Click on `https://chromereleases.googleblog.com/`

**Expected behavior**

Site works

**Screenshots**

<details>
<summary>Screen</summary>

![2023-12-22_183831](https://github.com/braveinnovators/url-blocklist/assets/111344219/f1a79f64-5b58-434e-a922-125516077422)
</details>

**Desktop (please complete the following information):**
 - OS: Windows 10 22H2
 - Browser: Google Chrome 120.0.6099.130
 - Version: uBO 1.54.0

**Comment by myroslavandriychuk** [comment]
@dportvine, thank you for reporting this issue. This rule should now work properly (update: 20231222.02)
